In [3]:
import pandas as pd

In [4]:
database_path = "../../Conicet_digital_11336_235509/contextualized_hate_speech_DATA"
filenames = ("dev-00000-of-00001.parquet", "test-00000-of-00001.parquet", "train-00000-of-00001.parquet")

## Lectura de base de datos

In [5]:
data_frames = {filename: pd.read_parquet(f"{database_path}/{filename}") for filename in filenames}

## Exploración Inicial

In [6]:
pd.DataFrame([(name, len(df)) for name, df in data_frames.items()], columns=("Archivo", "Filas"))

                        Archivo  Filas
0    dev-00000-of-00001.parquet   9106
1   test-00000-of-00001.parquet  11343
2  train-00000-of-00001.parquet  36420

In [7]:
df = data_frames["dev-00000-of-00001.parquet"]
df.head()

,id,title,text,context_tweet,HATEFUL,body,CALLS,WOMEN,LGBTI,RACISM,CLASS,POLITICS,DISABLED,APPEARANCE,CRIMINAL
0,337647,Wuhan celebra el fin de la cuarentena por el c...,@usuario Que cinismo,Wuhan celebra el fin de la cuarentena por el c...,0,Miles de chinos celebraron con euforia este mi...,0,0,0,0,0,0,0,0,0
1,336499,"Patricia Bullrich: ""Somos mirados por la socie...",@usuario La sociedad les dio la espalda en 201...,Patricia Bullrich: “Somos mirados por la socie...,0,"Recuperada de coronavirus, Patricia Bullrich r...",0,0,0,0,0,0,0,0,0
2,387046,¡Calu Rivero se desnudó para Instagram!,@usuario Revolucionario ponerse en bolas? Uy s...,🔥[¡CON DIGNITY!]🔥 ¡Calu Rivero se desnudó para...,0,Calu Rivero sorprendió en las redes sociales c...,0,0,0,0,0,0,0,0,0
3,350341,El líder piquetero Luis DElía pidió el indulto...,@usuario Como??..si deberia estar en la CARCEL...,El líder piquetero Luis D’Elía pidió el indult...,0,El dirigente social kirchnerista fue condenado...,0,0,0,0,0,0,0,0,0
4,336008,Cristina Kirchner no afloja: le pegó a Horacio...,@usuario Seamos serios si en la Pcia de Cornej...,Cristina Kirchner no afloja: le volvió a pegar...,0,"La vicepresidenta de la Nación, Cristina Kirch...",0,0,0,0,0,0,0,0,0

### Diccionario
|Variable|Descripción|
|--------|-----------|
|id|Identificador de fila|
|title|Título del posteo original|
|text|Texto del comentario|
|context_tweet|???|
|HATEFUL|Etiqueta (0-No discriminatorio, 1-discriminatorio)|
|body|Texto del posteo original|
|CALLS|Llamada a la violencia (0-no, 1-si)|
|WOMEN||
|LGBTI||
|RACISM||
|DISABLED||
|APPEARANCE||
|CRIMINAL||

In [9]:
# Variables de interés
variables =["id", "title", "text", "context_tweet", "HATEFUL", "body"]

### Proporción de comentarios discriminatorios por archivo

In [15]:
[(name, df["HATEFUL"].value_counts(normalize=True)) for name, df in data_frames.items()]

[('dev-00000-of-00001.parquet',
  HATEFUL
  0    0.847683
  1    0.152317
  Name: proportion, dtype: float64),
 ('test-00000-of-00001.parquet',
  HATEFUL
  0    0.841576
  1    0.158424
  Name: proportion, dtype: float64),
 ('train-00000-of-00001.parquet',
  HATEFUL
  0    0.848133
  1    0.151867
  Name: proportion, dtype: float64)]

In [26]:
pd.DataFrame([(name, len(df), df["title"].nunique()) for name, df in data_frames.items()], columns=("Archivo", "Filas", "Posteos"))

                        Archivo  Filas  Posteos
0    dev-00000-of-00001.parquet   9106      986
1   test-00000-of-00001.parquet  11343      248
2  train-00000-of-00001.parquet  36420      987